Práctica

In [1]:
i=4 #Entero

In [2]:
i**4 #Entero ; Mantiene el tipo de variable

256

In [3]:
i

4

In [4]:
i*=10 #Multiplica el valor almacenado en i por el escrito a la derecha del igual

In [5]:
i

40

In [6]:
i /=10 #Puede alterar el tipo de variable
i

4.0

In [7]:
i -= 1 #Mantiene el tipo de variable
i

3.0

In [8]:
i += 10 #Mantiene el tipo de variable
i

13.0

In [6]:
i=13

In [7]:
i //= 2
i

6

In [10]:
i%=3
i

1.0

In [11]:
contador=1

In [12]:
contador = contador + 1

In [13]:
contador

2

In [14]:
contador +=1
contador

3

# Parte 2

In [1]:
1==2 #Evalúa una igualdad

False

In [2]:
1<2 #>, <, <=, >=

True

In [3]:
1!=2 #Evalúar una diferencia

True

In [8]:
valor=1

In [4]:
cadena1, cadena2 = "Hola", "Adiós"
lista1, lista2 = [3,"Bienvenido",23], [True,"Gracias por su visita"]

In [5]:
c_cadenas= cadena1==cadena2

In [6]:
c_cadenas

False

In [7]:
c_listas= lista1==lista2
c_listas

False

In [8]:
a,b,c="Hola","Mundo"," "

In [11]:
a+c+b

'Hola Mundo'

In [12]:
a*3+c+b

'HolaHolaHola Mundo'

In [9]:
d="Marco Antonio"
#  0123456789

In [10]:
d

'Marco Antonio'

In [14]:
ult_letras=d[6:10] 
ult_letras

'Anto'

In [12]:
ult_letras!=d

True

In [13]:
ult_letras==d

False

In [20]:
edad=24/2
print("Mi edad es", edad)

Mi edad es 12.0


In [24]:
import numpy as np

In [25]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
mascara = a>3
mascara

array([False, False, False,  True,  True,  True,  True])

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7])